name: WPF Build (auto + manual)

on:
  push:
    branches:
      - main   # main에 커밋되면 자동 빌드
  workflow_dispatch:   # 버튼 눌러서 수동 빌드

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: dotnet restore wpfCCTV.sln


      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build WPF (.NET Framework)
        run: msbuild wpfCCTV.csproj /p:Configuration=Release

      - name: Check output
        run: |
          Get-ChildItem -Path ./bin/Release -Recurse

      - name: Zip output
        run: |
           Compress-Archive `
            -Path bin/Release/* `
            -DestinationPath wpfCCTV_Build.zip `
            -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CCTV-Binary
          path: wpfCCTV_Build.zip